version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crudb_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cruddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: mycrudapp
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cruddb
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: